const countries = [
    {
        name: 'Andorra',
        abbreviation: 'ad',
        dialingCode: '+376',
        svg:'',
    },
    {
        name: 'United Arab Emirates',
        abbreviation: 'ae',
        dialingCode: '+971',
        svg:'',
    },
    {
        name: 'Afghanistan',
        abbreviation: 'af',
        dialingCode: '+93',
        svg:'',
    },
    {
        name: 'Antigua and Barbuda',
        abbreviation: 'ag',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Anguilla',
        abbreviation: 'ai',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Albania',
        abbreviation: 'al',
        dialingCode: '+355',
        svg:'',
    },
    {
        name: 'Armenia',
        abbreviation: 'am',
        dialingCode: '+374',
        svg:'',
    },
    {
        name: 'Angola',
        abbreviation: 'ao',
        dialingCode: '+244',
        svg:'',
    },
    {
        name: 'Antarctica',
        abbreviation: 'aq',
        dialingCode: '',
        svg:'',
    },
    {
        name: 'Argentina',
        abbreviation: 'ar',
        dialingCode: '+54',
        svg:'',
    },
    {
        name: 'American Samoa',
        abbreviation: 'as',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Austria',
        abbreviation: 'at',
        dialingCode: '+43',
        svg:'',
    },
    {
        name: 'Australia',
        abbreviation: 'au',
        dialingCode: '+61',
        svg:'',
    },
    {
        name: 'Aruba',
        abbreviation: 'aw',
        dialingCode: '+297',
        svg:'',
    },
    {
        name: 'Åland Islands',
        abbreviation: 'ax',
        dialingCode: '+358',
        svg:'',
    },
    {
        name: 'Azerbaijan',
        abbreviation: 'az',
        dialingCode: '+994',
        svg:'',
    },
    {
        name: 'Bosnia and Herzegovina',
        abbreviation: 'ba',
        dialingCode: '+387',
        svg:'',
    },
    {
        name: 'Barbados',
        abbreviation: 'bb',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Bangladesh',
        abbreviation: 'bd',
        dialingCode: '+880',
        svg:'',
    },
    {
        name: 'Belgium',
        abbreviation: 'be',
        dialingCode: '+32',
        svg:'',
    },
    {
        name: 'Burkina Faso',
        abbreviation: 'bf',
        dialingCode: '+226',
        svg:'',
    },
    {
        name: 'Bulgaria',
        abbreviation: 'bg',
        dialingCode: '+359',
        svg:'',
    },
    {
        name: 'Bahrain',
        abbreviation: 'bh',
        dialingCode: '+973',
        svg:'',
    },
    {
        name: 'Burundi',
        abbreviation: 'bi',
        dialingCode: '+257',
        svg:'',
    },
    {
        name: 'Benin',
        abbreviation: 'bj',
        dialingCode: '+229',
        svg:'',
    },
    {
        name: 'Saint Barthélemy',
        abbreviation: 'bl',
        dialingCode: '+590',
        svg:'',
    },
    {
        name: 'Bermuda',
        abbreviation: 'bm',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Brunei',
        abbreviation: 'bn',
        dialingCode: '+673',
        svg:'',
    },
    {
        name: 'Bolivia',
        abbreviation: 'bo',
        dialingCode: '+591',
        svg:'',
    },
    {
        name: 'Bonaire',
        abbreviation: 'bq',
        dialingCode: '+599',
        svg:'',
    },
    {
        name: 'Brazil',
        abbreviation: 'br',
        dialingCode: '+55',
        svg:'',
    },
    {
        name: 'The Bahamas',
        abbreviation: 'bs',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Bhutan',
        abbreviation: 'bt',
        dialingCode: '+975',
        svg:'',
    },
    {
        name: 'Bouvet Island',
        abbreviation: 'bv',
        dialingCode: '',
        svg:'',
    },
    {
        name: 'Botswana',
        abbreviation: 'bw',
        dialingCode: '+267',
        svg:'',
    },
    {
        name: 'Belarus',
        abbreviation: 'by',
        dialingCode: '+375',
        svg:'',
    },
    {
        name: 'Belize',
        abbreviation: 'bz',
        dialingCode: '+501',
        svg:'',
    },
    {
        name: 'Canada',
        abbreviation: 'ca',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Cocos Islands',
        abbreviation: 'cc',
        dialingCode: '+61',
        svg:'',
    },
    {
        name: 'Democratic Republic of the Congo',
        abbreviation: 'cd',
        dialingCode: '+243',
        svg:'',
    },
    {
        name: 'Central African Republic',
        abbreviation: 'cf',
        dialingCode: '+236',
        svg:'',
    },
    {
        name: 'Republic of the Congo',
        abbreviation: 'cg',
        dialingCode: '+242',
        svg:'',
    },
    {
        name: 'Switzerland',
        abbreviation: 'ch',
        dialingCode: '+41',
        svg:'',
    },
    {
        name: 'Ivory Coast',
        abbreviation: 'ci',
        dialingCode: '+225',
        svg:'',
    },
    {
        name: 'Cook Islands',
        abbreviation: 'ck',
        dialingCode: '+682',
        svg:'',
    },
    {
        name: 'Chile',
        abbreviation: 'cl',
        dialingCode: '+56',
        svg:'',
    },
    {
        name: 'Cameroon',
        abbreviation: 'cm',
        dialingCode: '+237',
        svg:'',
    },
    {
        name: 'China',
        abbreviation: 'cn',
        dialingCode: '+86',
        svg:'',
    },
    {
        name: 'Colombia',
        abbreviation: 'co',
        dialingCode: '+57',
        svg:'',
    },
    {
        name: 'Costa Rica',
        abbreviation: 'cr',
        dialingCode: '+506',
        svg:'',
    },
    {
        name: 'Cuba',
        abbreviation: 'cu',
        dialingCode: '+53',
        svg:'',
    },
    {
        name: 'Cape Verde',
        abbreviation: 'cv',
        dialingCode: '+238',
        svg:'',
    },
    {
        name: 'Curaçao',
        abbreviation: 'cw',
        dialingCode: '+599',
        svg:'',
    },
    {
        name: 'Christmas Island',
        abbreviation: 'cx',
        dialingCode: '+61',
        svg:'',
    },
    {
        name: 'Cyprus',
        abbreviation: 'cy',
        dialingCode: '+357',
        svg:'',
    },
    {
        name: 'Czechia',
        abbreviation: 'cz',
        dialingCode: '+420',
        svg:'',
    },
    {
        name: 'Germany',
        abbreviation: 'de',
        dialingCode: '+49',
        svg:'',
    },
    {
        name: 'Djibouti',
        abbreviation: 'dj',
        dialingCode: '+253',
        svg:'',
    },
    {
        name: 'Denmark',
        abbreviation: 'dk',
        dialingCode: '+45',
        svg:'',
    },
    {
        name: 'Dominica',
        abbreviation: 'dm',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Dominican Republic',
        abbreviation: 'do',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Algeria',
        abbreviation: 'dz',
        dialingCode: '+213',
        svg:'',
    },
    {
        name: 'Ecuador',
        abbreviation: 'ec',
        dialingCode: '+593',
        svg:'',
    },
    {
        name: 'Estonia',
        abbreviation: 'ee',
        dialingCode: '+372',
        svg:'',
    },
    {
        name: 'Egypt',
        abbreviation: 'eg',
        dialingCode: '+20',
        svg:'',
    },
    {
        name: 'Western Sahara',
        abbreviation: 'eh',
        dialingCode: '+212',
        svg:'',
    },
    {
        name: 'Eritrea',
        abbreviation: 'er',
        dialingCode: '+291',
        svg:'',
    },
    {
        name: 'Spain',
        abbreviation: 'es',
        dialingCode: '+34',
        svg:'',
    },
    {
        name: 'Ethiopia',
        abbreviation: 'et',
        dialingCode: '+251',
        svg:'',
    },
    {
        name: 'European Union',
        abbreviation: 'eu',
        dialingCode: '', // No specific dialing code
        svg:'',
    },
    {
        name: 'Finland',
        abbreviation: 'fi',
        dialingCode: '+358',
        svg:'',
    },
    {
        name: 'Fiji',
        abbreviation: 'fj',
        dialingCode: '+679',
        svg:'',
    },
    {
        name: 'Falkland Islands',
        abbreviation: 'fk',
        dialingCode: '+500',
        svg:'',
    },
    {
        name: 'Micronesia',
        abbreviation: 'fm',
        dialingCode: '+691',
        svg:'',
    },
    {
        name: 'Faroe Islands',
        abbreviation: 'fo',
        dialingCode: '+298',
        svg:'',
    },
    {
        name: 'France',
        abbreviation: 'fr',
        dialingCode: '+33',
        svg:'',
    },
    {
        name: 'Gabon',
        abbreviation: 'ga',
        dialingCode: '+241',
        svg:'',
    },
    {
        name: 'United Kingdom',
        abbreviation: 'gb',
        dialingCode: '+44',
        svg:'',
    },
    {
        name: 'Grenada',
        abbreviation: 'gd',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Georgia',
        abbreviation: 'ge',
        dialingCode: '+995',
        svg:'',
    },
    {
        name: 'French Guiana',
        abbreviation: 'gf',
        dialingCode: '+594',
        svg:'',
    },
    {
        name: 'Guernsey',
        abbreviation: 'gg',
        dialingCode: '+44',
        svg:'',
    },
    {
        name: 'Ghana',
        abbreviation: 'gh',
        dialingCode: '+233',
        svg:'',
    },
    {
        name: 'Gibraltar',
        abbreviation: 'gi',
        dialingCode: '+350',
        svg:'',
    },
    {
        name: 'Greenland',
        abbreviation: 'gl',
        dialingCode: '+299',
        svg:'',
    },
    {
        name: 'Gambia',
        abbreviation: 'gm',
        dialingCode: '+220',
        svg:'',
    },
    {
        name: 'Guinea',
        abbreviation: 'gn',
        dialingCode: '+224',
        svg:'',
    },
    {
        name: 'Guadeloupe',
        abbreviation: 'gp',
        dialingCode: '+590',
        svg:'',
    },
    {
        name: 'Equatorial Guinea',
        abbreviation: 'gq',
        dialingCode: '+240',
        svg:'',
    },
    {
        name: 'Greece',
        abbreviation: 'gr',
        dialingCode: '+30',
        svg:'',
    },
    {
        name: 'South Georgia and the South Sandwich Islands',
        abbreviation: 'gs',
        dialingCode: '', // No specific dialing code
        svg:'',
    },
    {
        name: 'Guatemala',
        abbreviation: 'gt',
        dialingCode: '+502',
        svg:'',
    },
    {
        name: 'Guam',
        abbreviation: 'gu',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Guinea-Bissau',
        abbreviation: 'gw',
        dialingCode: '+245',
        svg:'',
    },
    {
        name: 'Guyana',
        abbreviation: 'gy',
        dialingCode: '+592',
        svg:'',
    },
    {
        name: 'Hong Kong',
        abbreviation: 'hk',
        dialingCode: '+852',
        svg:'',
    },
    {
        name: 'Heard Island and McDonald Islands',
        abbreviation: 'hm',
        dialingCode: '', // No specific dialing code
        svg:'',
    },
    {
        name: 'Honduras',
        abbreviation: 'hn',
        dialingCode: '+504',
        svg:'',
    },
    {
        name: 'Croatia',
        abbreviation: 'hr',
        dialingCode: '+385',
        svg:'',
    },
    {
        name: 'Haiti',
        abbreviation: 'ht',
        dialingCode: '+509',
        svg:'',
    },
    {
        name: 'Hungary',
        abbreviation: 'hu',
        dialingCode: '+36',
        svg:'',
    },
    {
        name: 'Indonesia',
        abbreviation: 'id',
        dialingCode: '+62',
        svg:'',
    },
    {
        name: 'Ireland',
        abbreviation: 'ie',
        dialingCode: '+353',
        svg:'',
    },
    {
        name: 'Israel',
        abbreviation: 'il',
        dialingCode: '+972',
        svg:'',
    },
    {
        name: 'Isle of Man',
        abbreviation: 'im',
        dialingCode: '+44',
        svg:'',
    },
    {
        name: 'India',
        abbreviation: 'in',
        dialingCode: '+91',
        svg:'',
    },
    {
        name: 'British Indian Ocean Territory',
        abbreviation: 'io',
        dialingCode: '+246',
        svg:'',
    },
    {
        name: 'Iraq',
        abbreviation: 'iq',
        dialingCode: '+964',
        svg:'',
    },
    {
        name: 'Iran',
        abbreviation: 'ir',
        dialingCode: '+98',
        svg:'',
    },
    {
        name: 'Iceland',
        abbreviation: 'is',
        dialingCode: '+354',
        svg:'',
    },
    {
        name: 'Italy',
        abbreviation: 'it',
        dialingCode: '+39',
        svg:'',
    },
    {
        name: 'Jersey',
        abbreviation: 'je',
        dialingCode: '+44',
        svg:'',
    },
    {
        name: 'Jamaica',
        abbreviation: 'jm',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Jordan',
        abbreviation: 'jo',
        dialingCode: '+962',
        svg:'',
    },
    {
        name: 'Japan',
        abbreviation: 'jp',
        dialingCode: '+81',
        svg:'',
    },
    {
        name: 'Kenya',
        abbreviation: 'ke',
        dialingCode: '+254',
        svg:'',
    },
    {
        name: 'Kyrgyzstan',
        abbreviation: 'kg',
        dialingCode: '+996',
        svg:'',
    },
    {
        name: 'Cambodia',
        abbreviation: 'kh',
        dialingCode: '+855',
        svg:'',
    },
    {
        name: 'Kiribati',
        abbreviation: 'ki',
        dialingCode: '+686',
        svg:'',
    },
    {
        name: 'Comoros',
        abbreviation: 'km',
        dialingCode: '+269',
        svg:'',
    },
    {
        name: 'Saint Kitts and Nevis',
        abbreviation: 'kn',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'North Korea',
        abbreviation: 'kp',
        dialingCode: '+850',
        svg:'',
    },
    {
        name: 'South Korea',
        abbreviation: 'kr',
        dialingCode: '+82',
        svg:'',
    },
    {
        name: 'Kuwait',
        abbreviation: 'kw',
        dialingCode: '+965',
        svg:'',
    },
    {
        name: 'Cayman Islands',
        abbreviation: 'ky',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Kazakhstan',
        abbreviation: 'kz',
        dialingCode: '+7',
        svg:'',
    },
    {
        name: 'Laos',
        abbreviation: 'la',
        dialingCode: '+856',
        svg:'',
    },
    {
        name: 'Lebanon',
        abbreviation: 'lb',
        dialingCode: '+961',
        svg:'',
    },
    {
        name: 'Saint Lucia',
        abbreviation: 'lc',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Liechtenstein',
        abbreviation: 'li',
        dialingCode: '+423',
        svg:'',
    },
    {
        name: 'Sri Lanka',
        abbreviation: 'lk',
        dialingCode: '+94',
        svg:'',
    },
    {
        name: 'Liberia',
        abbreviation: 'lr',
        dialingCode: '+231',
        svg:'',
    },
    {
        name: 'Lesotho',
        abbreviation: 'ls',
        dialingCode: '+266',
        svg:'',
    },
    {
        name: 'Lithuania',
        abbreviation: 'lt',
        dialingCode: '+370',
        svg:'',
    },
    {
        name: 'Luxembourg',
        abbreviation: 'lu',
        dialingCode: '+352',
        svg:'',
    },
    {
        name: 'Latvia',
        abbreviation: 'lv',
        dialingCode: '+371',
        svg:'',
    },
    {
        name: 'Libya',
        abbreviation: 'ly',
        dialingCode: '+218',
        svg:'',
    },
    {
        name: 'Morocco',
        abbreviation: 'ma',
        dialingCode: '+212',
        svg:'',
    },
    {
        name: 'Monaco',
        abbreviation: 'mc',
        dialingCode: '+377',
        svg:'',
    },
    {
        name: 'Moldova',
        abbreviation: 'md',
        dialingCode: '+373',
        svg:'',
    },
    {
        name: 'Montenegro',
        abbreviation: 'me',
        dialingCode: '+382',
        svg:'',
    },
    {
        name: 'Saint Martin',
        abbreviation: 'mf',
        dialingCode: '+590',
        svg:'',
    },
    {
        name: 'Madagascar',
        abbreviation: 'mg',
        dialingCode: '+261',
        svg:'',
    },
    {
        name: 'Marshall Islands',
        abbreviation: 'mh',
        dialingCode: '+692',
        svg:'',
    },
    {
        name: 'North Macedonia',
        abbreviation: 'mk',
        dialingCode: '+389',
        svg:'',
    },
    {
        name: 'Mali',
        abbreviation: 'ml',
        dialingCode: '+223',
        svg:'',
    },
    {
        name: 'Myanmar',
        abbreviation: 'mm',
        dialingCode: '+95',
        svg:'',
    },
    {
        name: 'Mongolia',
        abbreviation: 'mn',
        dialingCode: '+976',
        svg:'',
    },
    {
        name: 'Macao',
        abbreviation: 'mo',
        dialingCode: '+853',
        svg:'',
    },
    {
        name: 'Northern Mariana Islands',
        abbreviation: 'mp',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Martinique',
        abbreviation: 'mq',
        dialingCode: '+596',
        svg:'',
    },
    {
        name: 'Mauritania',
        abbreviation: 'mr',
        dialingCode: '+222',
        svg:'',
    },
    {
        name: 'Montserrat',
        abbreviation: 'ms',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Malta',
        abbreviation: 'mt',
        dialingCode: '+356',
        svg:'',
    },
    {
        name: 'Mauritius',
        abbreviation: 'mu',
        dialingCode: '+230',
        svg:'',
    },
    {
        name: 'Maldives',
        abbreviation: 'mv',
        dialingCode: '+960',
        svg:'',
    },
    {
        name: 'Malawi',
        abbreviation: 'mw',
        dialingCode: '+265',
        svg:'',
    },
    {
        name: 'Mexico',
        abbreviation: 'mx',
        dialingCode: '+52',
        svg:'',
    },
    {
        name: 'Malaysia',
        abbreviation: 'my',
        dialingCode: '+60',
        svg:'',
    },
    {
        name: 'Mozambique',
        abbreviation: 'mz',
        dialingCode: '+258',
        svg:'',
    },
    {
        name: 'Namibia',
        abbreviation: 'na',
        dialingCode: '+264',
        svg:'',
    },
    {
        name: 'New Caledonia',
        abbreviation: 'nc',
        dialingCode: '+687',
        svg:'',
    },
    {
        name: 'Niger',
        abbreviation: 'ne',
        dialingCode: '+227',
        svg:'',
    },
    {
        name: 'Norfolk Island',
        abbreviation: 'nf',
        dialingCode: '+672',
        svg:'',
    },
    {
        name: 'Nigeria',
        abbreviation: 'ng',
        dialingCode: '+234',
        svg:'',
    },
    {
        name: 'Nicaragua',
        abbreviation: 'ni',
        dialingCode: '+505',
        svg:'',
    },
    {
        name: 'Netherlands',
        abbreviation: 'nl',
        dialingCode: '+31',
        svg:'',
    },
    {
        name: 'Norway',
        abbreviation: 'no',
        dialingCode: '+47',
        svg:'',
    },
    {
        name: 'Nepal',
        abbreviation: 'np',
        dialingCode: '+977',
        svg:'',
    },
    {
        name: 'Nauru',
        abbreviation: 'nr',
        dialingCode: '+674',
        svg:'',
    },
    {
        name: 'Niue',
        abbreviation: 'nu',
        dialingCode: '+683',
        svg:'',
    },
    {
        name: 'New Zealand',
        abbreviation: 'nz',
        dialingCode: '+64',
        svg:'',
    },
    {
        name: 'Oman',
        abbreviation: 'om',
        dialingCode: '+968',
        svg:'',
    },
    {
        name: 'Panama',
        abbreviation: 'pa',
        dialingCode: '+507',
        svg:'',
    },
    {
        name: 'Peru',
        abbreviation: 'pe',
        dialingCode: '+51',
        svg:'',
    },
    {
        name: 'French Polynesia',
        abbreviation: 'pf',
        dialingCode: '+689',
        svg:'',
    },
    {
        name: 'Papua New Guinea',
        abbreviation: 'pg',
        dialingCode: '+675',
        svg:'',
    },
    {
        name: 'Philippines',
        abbreviation: 'ph',
        dialingCode: '+63',
        svg:'',
    },
    {
        name: 'Pakistan',
        abbreviation: 'pk',
        dialingCode: '+92',
        svg:'',
    },
    {
        name: 'Poland',
        abbreviation: 'pl',
        dialingCode: '+48',
        svg:'',
    },
    {
        name: 'Saint Pierre and Miquelon',
        abbreviation: 'pm',
        dialingCode: '+508',
        svg:'',
    },
    {
        name: 'Pitcairn Islands',
        abbreviation: 'pn',
        dialingCode: '+64',
        svg:'',
    },
    {
        name: 'Puerto Rico',
        abbreviation: 'pr',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Palestine',
        abbreviation: 'ps',
        dialingCode: '+970',
        svg:'',
    },
    {
        name: 'Portugal',
        abbreviation: 'pt',
        dialingCode: '+351',
        svg:'',
    },
    {
        name: 'Palau',
        abbreviation: 'pw',
        dialingCode: '+680',
        svg:'',
    },
    {
        name: 'Paraguay',
        abbreviation: 'py',
        dialingCode: '+595',
        svg:'',
    },
    {
        name: 'Qatar',
        abbreviation: 'qa',
        dialingCode: '+974',
        svg:'',
    },
    {
        name: 'Réunion',
        abbreviation: 're',
        dialingCode: '+262',
        svg:'',
    },
    {
        name: 'Romania',
        abbreviation: 'ro',
        dialingCode: '+40',
        svg:'',
    },
    {
        name: 'Serbia',
        abbreviation: 'rs',
        dialingCode: '+381',
        svg:'',
    },
    {
        name: 'Russia',
        abbreviation: 'ru',
        dialingCode: '+7',
        svg:'',
    },
    {
        name: 'Rwanda',
        abbreviation: 'rw',
        dialingCode: '+250',
        svg:'',
    },
    {
        name: 'Saudi Arabia',
        abbreviation: 'sa',
        dialingCode: '+966',
        svg:'',
    },
    {
        name: 'Solomon Islands',
        abbreviation: 'sb',
        dialingCode: '+677',
        svg:'',
    },
    {
        name: 'Seychelles',
        abbreviation: 'sc',
        dialingCode: '+248',
        svg:'',
    },
    {
        name: 'Sudan',
        abbreviation: 'sd',
        dialingCode: '+249',
        svg:'',
    },
    {
        name: 'Sweden',
        abbreviation: 'se',
        dialingCode: '+46',
        svg:'',
    },
    {
        name: 'Singapore',
        abbreviation: 'sg',
        dialingCode: '+65',
        svg:'',
    },
    {
        name: 'Saint Helena',
        abbreviation: 'sh',
        dialingCode: '+290',
        svg:'',
    },
    {
        name: 'Slovenia',
        abbreviation: 'si',
        dialingCode: '+386',
        svg:'',
    },
    {
        name: 'Svalbard and Jan Mayen',
        abbreviation: 'sj',
        dialingCode: '+47',
        svg:'',
    },
    {
        name: 'Slovakia',
        abbreviation: 'sk',
        dialingCode: '+421',
        svg:'',
    },
    {
        name: 'Sierra Leone',
        abbreviation: 'sl',
        dialingCode: '+232',
        svg:'',
    },
    {
        name: 'San Marino',
        abbreviation: 'sm',
        dialingCode: '+378',
        svg:'',
    },
    {
        name: 'Senegal',
        abbreviation: 'sn',
        dialingCode: '+221',
        svg:'',
    },
    {
        name: 'Somalia',
        abbreviation: 'so',
        dialingCode: '+252',
        svg:'',
    },
    {
        name: 'Suriname',
        abbreviation: 'sr',
        dialingCode: '+597',
        svg:'',
    },
    {
        name: 'South Sudan',
        abbreviation: 'ss',
        dialingCode: '+211',
        svg:'',
    },
    {
        name: 'São Tomé and Príncipe',
        abbreviation: 'st',
        dialingCode: '+239',
        svg:'',
    },
    {
        name: 'El Salvador',
        abbreviation: 'sv',
        dialingCode: '+503',
        svg:'',
    },
    {
        name: 'Sint Maarten',
        abbreviation: 'sx',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Syria',
        abbreviation: 'sy',
        dialingCode: '+963',
        svg:'',
    },
    {
        name: 'Turks and Caicos Islands',
        abbreviation: 'tc',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Chad',
        abbreviation: 'td',
        dialingCode: '+235',
        svg:'',
    },
    {
        name: 'Togo',
        abbreviation: 'tg',
        dialingCode: '+228',
        svg:'',
    },
    {
        name: 'Thailand',
        abbreviation: 'th',
        dialingCode: '+66',
        svg:'',
    },
    {
        name: 'Tajikistan',
        abbreviation: 'tj',
        dialingCode: '+992',
        svg:'',
    },
    {
        name: 'Tokelau',
        abbreviation: 'tk',
        dialingCode: '+690',
        svg:'',
    },
    {
        name: 'Timor-Leste',
        abbreviation: 'tl',
        dialingCode: '+670',
        svg:'',
    },
    {
        name: 'Turkmenistan',
        abbreviation: 'tm',
        dialingCode: '+993',
        svg:'',
    },
    {
        name: 'Tunisia',
        abbreviation: 'tn',
        dialingCode: '+216',
        svg:'',
    },
    {
        name: 'Tonga',
        abbreviation: 'to',
        dialingCode: '+676',
        svg:'',
    },
    {
        name: 'Turkey',
        abbreviation: 'tr',
        dialingCode: '+90',
        svg:'',
    },
    {
        name: 'Trinidad and Tobago',
        abbreviation: 'tt',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Tuvalu',
        abbreviation: 'tv',
        dialingCode: '+688',
        svg:'',
    },
    {
        name: 'Taiwan',
        abbreviation: 'tw',
        dialingCode: '+886',
        svg:'',
    },
    {
        name: 'Tanzania',
        abbreviation: 'tz',
        dialingCode: '+255',
        svg:'',
    },
    {
        name: 'Ukraine',
        abbreviation: 'ua',
        dialingCode: '+380',
        svg:'',
    },
    {
        name: 'Uganda',
        abbreviation: 'ug',
        dialingCode: '+256',
        svg:'',
    },
    {
        name: 'United States Minor Outlying Islands',
        abbreviation: 'um',
        dialingCode: '', // No specific dialing code
        svg:'',
    },
    {
        name: 'United States',
        abbreviation: 'us',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Uruguay',
        abbreviation: 'uy',
        dialingCode: '+598',
        svg:'',
    },
    {
        name: 'Uzbekistan',
        abbreviation: 'uz',
        dialingCode: '+998',
        svg:'',
    },
    {
        name: 'Vatican City',
        abbreviation: 'va',
        dialingCode: '+379',
        svg:'',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        abbreviation: 'vc',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Venezuela',
        abbreviation: 've',
        dialingCode: '+58',
        svg:'',
    },
    {
        name: 'British Virgin Islands',
        abbreviation: 'vg',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'U.S. Virgin Islands',
        abbreviation: 'vi',
        dialingCode: '+1',
        svg:'',
    },
    {
        name: 'Vietnam',
        abbreviation: 'vn',
        dialingCode: '+84',
        svg:'',
    },
    {
        name: 'Vanuatu',
        abbreviation: 'vu',
        dialingCode: '+678',
        svg:'',
    },
    {
        name: 'Wallis and Futuna',
        abbreviation: 'wf',
        dialingCode: '+681',
        svg:'',
    },
    {
        name: 'Kosovo',
        abbreviation: 'xk',
        dialingCode: '+383',
        svg:'',
    },
    {
        name: 'Yemen',
        abbreviation: 'ye',
        dialingCode: '+967',
        svg:'',
    },
    {
        name: 'Mayotte',
        abbreviation: 'yt',
        dialingCode: '+262',
        svg:'',
    },
    {
        name: 'South Africa',
        abbreviation: 'za',
        dialingCode: '+27',
        svg:'',
    },
    {
        name: 'Zambia',
        abbreviation: 'zm',
        dialingCode: '+260',
        svg:'',
    },
    {
        name: 'Zimbabwe',
        abbreviation: 'zw',
        dialingCode: '+263',
        svg:'',
    },
];

// Assigning SVG values and Populates in Countries Array

export function populateSvgForCountries(countries) {
    for (const country of countries) {
      if (country.abbreviation && !country.svg) {
        country.svg = `${country.abbreviation}.svg`;
      }
    }
}

populateSvgForCountries(countries);

// Sorts

countries.sort((a, b) => a.name.localeCompare(b.name));

// Filter

export const filteredCountriesFromUtil = countries.filter(country => country.dialingCode !== '');

