const languageOptions = [
    { value: "af", label: "Afrikaans" },
    { value: "az", label: "Azərbaycan" },
    { value: "bs", label: "Bosanski" },
    { value: "ca", label: "Català" },
    { value: "cs", label: "Čeština" },
    { value: "cy", label: "Cymraeg" },
    { value: "da", label: "Dansk" },
    { value: "de", label: "Deutsch" },
    { value: "et", label: "Eesti" },
    { value: "en-GB", label: "English (United Kingdom)" },
    { value: "en-US", label: "English (United States)" },
    { value: "es-ES", label: "Español (España)" },
    { value: "es-LA", label: "Español (Latinoamérica)" },
    { value: "eu", label: "Euskara" },
    { value: "fil", label: "Filipino" },
    { value: "fr-CA", label: "Français (Canada)" },
    { value: "fr-FR", label: "Français (France)" },
    { value: "ga", label: "Gaeilge" },
    { value: "gl", label: "Galego" },
    { value: "hr", label: "Hrvatski" },
    { value: "id", label: "Indonesia" },
    { value: "zu", label: "IsiZulu" },
    { value: "is", label: "Íslenska" },
    { value: "it", label: "Italiano" },
    { value: "sw", label: "Kiswahili" },
    { value: "lv", label: "Latviešu" },
    { value: "lt", label: "Lietuvių" },
    { value: "hu", label: "Magyar" },
    { value: "ms", label: "Melayu" },
    { value: "nl", label: "Nederlands" },
    { value: "no", label: "Norsk" },
    { value: "uz", label: "O'zbek" },
    { value: "pl", label: "Polski" },
    { value: "pt-BR", label: "Português (Brasil)" },
    { value: "pt-PT", label: "Português (Portugal)" },
    { value: "ro", label: "Română" },
    { value: "sq", label: "Shqip" },
    { value: "sk", label: "Slovenčina" },
    { value: "sl", label: "Slovenščina" },
    { value: "sr-Latn", label: "Srpski (Latinica)" },
    { value: "fi", label: "Suomi" },
    { value: "sv", label: "Svenska" },
    { value: "vi", label: "Tiếng Việt" },
    { value: "tr", label: "Türkçe" },
    { value: "el", label: "Ελληνικά" },
    { value: "be", label: "Беларуская" },
    { value: "bg", label: "Български" },
    { value: "ky", label: "Кыргызча" },
    { value: "kk", label: "Қазақ тілі" },
    { value: "mk", label: "Македонски" },
    { value: "mn", label: "Монгол" },
    { value: "ru", label: "Русский" },
    { value: "sr-Cyrl", label: "Српски (ћирилица)" },
    { value: "uk", label: "Українська" },
    { value: "ka", label: "ქართული" },
    { value: "hy", label: "Հայերեն" },
    { value: "he", label: "‫עברית‬‎" },
    { value: "ur", label: "‫اردو‬‎" },
    { value: "ar", label: "‫العربية‬‎" },
    { value: "fa", label: "‫فارسی‬‎" },
    { value: "am", label: "አማርኛ" },
    { value: "ne", label: "नेपाली" },
    { value: "mr", label: "मराठी" },
    { value: "hi", label: "हिन्दी" },
    { value: "as", label: "অসমীয়া" },
    { value: "bn", label: "বাংলা" },
    { value: "pa", label: "ਪੰਜਾਬੀ" },
    { value: "gu", label: "ગુજરાતી" },
    { value: "or", label: "ଓଡ଼ିଆ" },
    { value: "ta", label: "தமிழ்" },
    { value: "te", label: "తెలుగు" },
    { value: "kn", label: "ಕನ್ನಡ" },
    { value: "ml", label: "മലയാളം" },
    { value: "si", label: "සිංහල" },
    { value: "th", label: "ไทย" },
    { value: "lo", label: "ລາວ" },
    { value: "my", label: "မြန်မာ" },
    { value: "km", label: "ខ្មែរ" },
    { value: "ko", label: "한국어" },
    { value: "zh-HK", label: "中文（香港）" },
    { value: "ja", label: "日本語" },
    { value: "zh-CN", label: "简体中文" },
    { value: "zh-TW", label: "繁體中文" }
];

export default languageOptions;
